import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { motion } from "motion/react";
import {
  Search,
  Filter,
  ArrowUpRight,
  GitBranch,
  Clock,
  CheckCircle2,
  XCircle,
  AlertTriangle,
  Loader2,
  Layers,
  Activity,
  Brain,
  Hash,
} from "lucide-react";
import { formatDuration, formatRelative } from "../lib/display";
import { useLiveSessions, type LiveSessionSummary } from "../lib/useApi";
import { Badge } from "../components/ui/Badge";
import { Sparkline } from "../components/ui/Sparkline";
import { AnimatedNumber } from "../components/ui/AnimatedNumber";
import { SourceTag } from "../components/ui/SourceTag";
import { cn } from "../lib/cn";

type StatusFilter = "all" | "finished" | "running";

const statusFilters: { id: StatusFilter; label: string }[] = [
  { id: "all", label: "All" },
  { id: "finished", label: "Finished" },
  { id: "running", label: "Running" },
];

export function SessionsPage() {
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState<StatusFilter>("all");
  const {
    data: sessions,
    source,
    loading,
    error,
    refresh,
  } = useLiveSessions();

  const filtered = useMemo(() => {
    return sessions.filter((s) => {
      const matchStatus =
        status === "all" ||
        (status === "finished" && (s.status === "finished" || s.status === "success")) ||
        (status === "running" && s.status === "running");
      const q = query.trim().toLowerCase();
      const matchQuery =
        !q ||
        s.task.toLowerCase().includes(q) ||
        (s.repoPath ?? "").toLowerCase().includes(q) ||
        (s.branch ?? "").toLowerCase().includes(q) ||
        s.id.toLowerCase().includes(q);
      return matchStatus && matchQuery;
    });
  }, [sessions, query, status]);

  const stats = useMemo(() => {
    const total = sessions.length;
    const finished = sessions.filter(
      (s) => s.status === "finished" || s.status === "success"
    ).length;
    const totalCards = sessions.reduce((acc, s) => acc + (s.memoryCardCount || 0), 0);
    const totalActions = sessions.reduce((acc, s) => acc + (s.actionCount || 0), 0);
    return { total, finished, totalCards, totalActions };
  }, [sessions]);

  return (
    <div className="px-4 py-8 lg:px-8">
      <div className="mx-auto max-w-7xl">
        <header className="flex flex-wrap items-end justify-between gap-4">
          <div>
            <div className="mb-3 flex flex-wrap items-center gap-2">
              <Badge tone="electric">
                <Activity className="h-3 w-3" /> dashboard
              </Badge>
              <SourceTag source={source} loading={loading} onRefresh={refresh} />
            </div>
            <h1 className="font-serif text-[36px] leading-tight text-white md:text-[44px]">
              Every agent session, captured.
            </h1>
            <p className="mt-2 max-w-xl text-[14px] text-white/60">
              Sessions are read straight from{" "}
              <span className="font-mono text-white/80">.witsmith/sessions/</span> via{" "}
              <span className="font-mono text-white/80">/api/sessions</span>.
            </p>
          </div>
          <div className="flex items-center gap-2">
            <Link
              to="/cli"
              className="inline-flex h-10 items-center gap-2 rounded-full border border-white/10 bg-white/[0.03] px-4 font-mono text-[12.5px] text-white/80 hover:border-[color:var(--color-violet-glow)]/40"
            >
              <span className="text-[color:var(--color-violet-glow)]">$</span> witsmith start
            </Link>
          </div>
        </header>

        {/* Stats — only real fields the backend exposes */}
        <div className="mt-8 grid grid-cols-2 gap-3 sm:gap-4 md:grid-cols-4">
          <StatCard
            icon={<Layers className="h-4 w-4" />}
            label="Sessions"
            value={<AnimatedNumber value={stats.total} />}
            sub="Recorded on disk"
            spark={[stats.total]}
          />
          <StatCard
            icon={<CheckCircle2 className="h-4 w-4" />}
            label="Finished"
            value={
              <>
                <AnimatedNumber value={stats.finished} />
                <span className="text-white/35"> / {stats.total || "—"}</span>
              </>
            }
            sub={
              stats.total > 0
                ? `${Math.round((stats.finished / stats.total) * 100)}% finished`
                : "—"
            }
            spark={[stats.finished]}
            color="var(--color-success)"
          />
          <StatCard
            icon={<Brain className="h-4 w-4" />}
            label="Memory cards"
            value={<AnimatedNumber value={stats.totalCards} />}
            sub="Generated by CLōD"
            spark={[stats.totalCards]}
            color="var(--color-violet-glow)"
          />
          <StatCard
            icon={<Hash className="h-4 w-4" />}
            label="Actions"
            value={<AnimatedNumber value={stats.totalActions} />}
            sub="Across all sessions"
            spark={[stats.totalActions]}
            color="var(--color-acid)"
          />
        </div>

        {/* Filters */}
        <div className="mt-8 flex flex-wrap items-center gap-3">
          <div className="relative flex-1 min-w-[220px]">
            <Search className="absolute left-3 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-white/40" />
            <input
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              placeholder="Search by task, branch, id…"
              className="h-10 w-full rounded-full border border-white/10 bg-white/[0.03] pl-9 pr-3 text-[13.5px] text-white placeholder-white/35 outline-none focus:border-[color:var(--color-acid)]/40 focus:bg-white/[0.05]"
            />
          </div>
          <div className="flex items-center gap-1 rounded-full border border-white/10 bg-white/[0.02] p-1">
            {statusFilters.map((s) => (
              <button
                key={s.id}
                onClick={() => setStatus(s.id)}
                className={cn(
                  "relative rounded-full px-3 py-1.5 text-[12.5px] font-medium transition-colors",
                  status === s.id ? "text-white" : "text-white/65 hover:text-white"
                )}
              >
                {status === s.id && (
                  <motion.span
                    layoutId="status-pill"
                    className="absolute inset-0 rounded-full bg-gradient-to-b from-[#c47bff] to-[#7e14ff]"
                    transition={{ type: "spring", stiffness: 320, damping: 30 }}
                  />
                )}
                <span className="relative">{s.label}</span>
              </button>
            ))}
          </div>
          <button
            onClick={refresh}
            className="inline-flex h-10 items-center gap-2 rounded-full border border-white/10 px-3 text-[12.5px] text-white/65 hover:border-white/20 hover:text-white"
          >
            <Filter className="h-3.5 w-3.5" /> Refresh
          </button>
        </div>

        {/* Sessions table */}
        <div className="mt-6 overflow-hidden rounded-2xl border border-white/10 bg-[color:var(--color-surface)]/60">
          <div className="hidden grid-cols-[2.5fr_1fr_0.8fr_1fr_0.7fr] gap-4 border-b border-white/5 bg-white/[0.02] px-5 py-3 text-[10.5px] font-medium uppercase tracking-[0.16em] text-white/45 lg:grid">
            <div>Task</div>
            <div>Branch</div>
            <div>Files</div>
            <div>Actions · Memory</div>
            <div className="text-right">Started</div>
          </div>

          {error && (
            <div className="px-5 py-12 text-center text-sm text-[color:var(--color-danger)]">
              Backend error: {error}
            </div>
          )}

          {!error && filtered.length === 0 && !loading && (
            <div className="px-5 py-16 text-center text-sm text-white/55">
              {sessions.length === 0
                ? "No sessions recorded yet. Run witsmith start + finish in a witsmith-instrumented repo."
                : "No sessions match these filters."}
            </div>
          )}

          {!error && loading && sessions.length === 0 && (
            <div className="flex items-center justify-center px-5 py-16 text-sm text-white/55">
              <Loader2 className="mr-2 h-4 w-4 animate-spin" /> loading…
            </div>
          )}

          <ul>
            {filtered.map((s, i) => (
              <motion.li
                key={s.id}
                initial={{ opacity: 0, y: 8 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.35, delay: i * 0.04 }}
                className="border-b border-white/5 last:border-b-0"
              >
                <Link
                  to={`/sessions/${encodeURIComponent(s.id)}`}
                  className="group block px-5 py-4 transition-colors hover:bg-white/[0.025]"
                >
                  <div className="grid grid-cols-1 items-center gap-4 lg:grid-cols-[2.5fr_1fr_0.8fr_1fr_0.7fr]">
                    <div className="flex items-start gap-3">
                      <StatusGlyph status={s.status} />
                      <div className="min-w-0 flex-1">
                        <div className="flex items-center gap-2">
                          <span className="truncate text-[14.5px] font-medium text-white group-hover:text-[color:var(--color-acid)]">
                            {s.task || "(no task)"}
                          </span>
                          <ArrowUpRight className="h-3.5 w-3.5 -translate-x-1 text-white/30 opacity-0 transition-all group-hover:translate-x-0 group-hover:opacity-100" />
                        </div>
                        <div className="mt-0.5 flex flex-wrap items-center gap-1.5 text-[11.5px] text-white/45">
                          <span className="font-mono">{s.id}</span>
                          {s.baseCommit && (
                            <>
                              <span>·</span>
                              <span className="font-mono">{s.baseCommit.slice(0, 7)}</span>
                            </>
                          )}
                        </div>
                      </div>
                    </div>

                    <div className="flex items-center gap-1.5 text-[12.5px] text-white/65">
                      <GitBranch className="h-3.5 w-3.5 text-white/40" />
                      <span className="truncate font-mono text-[12px]">
                        {s.branch || "—"}
                      </span>
                    </div>

                    <div className="flex items-center gap-3 text-[12.5px]">
                      <span className="font-mono text-white/85">
                        {s.changedFiles?.length ?? 0}
                      </span>
                      <span className="text-white/45 text-[11px]">files</span>
                    </div>

                    <div className="flex items-center gap-3 text-[12.5px]">
                      <span className="font-mono text-white/85">{s.actionCount}</span>
                      <span className="text-white/40">·</span>
                      <span className="font-mono text-[color:var(--color-violet-glow)]">
                        {s.memoryCardCount}
                      </span>
                      <span className="text-white/45 text-[11px]">cards</span>
                    </div>

                    <div className="flex flex-col items-start text-[12px] text-white/65 lg:items-end">
                      <span className="flex items-center gap-1.5">
                        <Clock className="h-3 w-3 text-white/40" />
                        {durationFor(s)}
                      </span>
                      <span className="text-[11px] text-white/40">
                        {formatRelative(s.startedAt)}
                      </span>
                    </div>
                  </div>
                </Link>
              </motion.li>
            ))}
          </ul>
        </div>
      </div>
    </div>
  );
}

function durationFor(s: LiveSessionSummary): string {
  if (!s.startedAt || !s.finishedAt) return "—";
  const ms = new Date(s.finishedAt).getTime() - new Date(s.startedAt).getTime();
  return formatDuration(ms);
}

function StatCard({
  icon,
  label,
  value,
  sub,
  spark,
  color = "var(--color-electric)",
}: {
  icon: React.ReactNode;
  label: string;
  value: React.ReactNode;
  sub: string;
  spark: number[];
  color?: string;
}) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.45 }}
      className="relative overflow-hidden rounded-2xl border border-white/10 bg-[color:var(--color-surface)] p-4"
    >
      <div
        aria-hidden
        className="pointer-events-none absolute -right-12 -top-12 h-36 w-36 rounded-full opacity-20 blur-3xl"
        style={{ background: color }}
      />
      <div className="flex items-center justify-between">
        <span className="flex items-center gap-1.5 text-[10.5px] font-medium uppercase tracking-[0.16em] text-white/45">
          <span style={{ color }}>{icon}</span> {label}
        </span>
      </div>
      <div className="mt-2 font-serif text-[34px] leading-none text-white">{value}</div>
      <div className="mt-2 flex items-end justify-between">
        <span className="text-[11.5px] text-white/45">{sub}</span>
        <Sparkline values={spark.length > 0 ? spark : [0]} width={70} height={24} color={color} />
      </div>
    </motion.div>
  );
}

function StatusGlyph({ status }: { status: string }) {
  const map: Record<string, { Icon: typeof CheckCircle2; color: string }> = {
    finished: { Icon: CheckCircle2, color: "var(--color-success)" },
    success: { Icon: CheckCircle2, color: "var(--color-success)" },
    failed: { Icon: XCircle, color: "var(--color-danger)" },
    partial: { Icon: AlertTriangle, color: "var(--color-warn)" },
    running: { Icon: Loader2, color: "var(--color-electric)" },
  };
  const { Icon, color } = map[status] ?? map.finished;
  return (
    <div
      className="grid h-9 w-9 shrink-0 place-items-center rounded-xl border"
      style={{
        background: `color-mix(in oklab, ${color} 10%, transparent)`,
        borderColor: `color-mix(in oklab, ${color} 30%, transparent)`,
      }}
    >
      <Icon
        className={cn("h-4 w-4", status === "running" && "animate-spin")}
        style={{ color }}
      />
    </div>
  );
}
